[connections.default]
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
database = "GIT"
schema = "PUBLIC"
account = "<INSERT YOUR ACCOUNT IDENTIFIER>"
user = "<INSERT YOUR USERNAME>"
password = "<INSERT YOUR PASSWORD>"
